server:
  port: 9991
  contextPath: /auth

security:
  user:
    password: password
  sessions: if-required
  oauth2:
      client:
        client-id: acme
        client-secret: acmesecret
        scope: read,write
        auto-approve-scopes: '.*'

facebook:
  client:
    clientId: YOUR_FACEBOOK_CLIENT_ID
    clientSecret: YOUR_FACEBOOK_CLIENT_SECRET
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: DEBUG